### ISSUE TITLE
nit: While cool, is this a repetition of the other TryProcess before?

### ISSUE THREAD

**Issue by phuvp** [erikgassler/Demo#2]
https://github.com/erikgassler/Demo/blob/476af408a9ffa3ac61c1c604e8cd5d9e8c672819/WebApp/Server/Controllers/ControllerCore.cs#L16

**Comment by erikgassler** [comment]
Yes, it is essentially a duplicate. The only real reason for having 2 different methods that essentially perform the same task comes to logging and the fact that I want anything using these methods to automatically log specific details about the process - specifically who's calling them.
The one used in the shared library can be used by either Client or Server solutions. The other is used strictly by the server and thus can take advantage of the more desired [Caller...] attributes to automatically inject the calling method, file, and line number which I want for logging purposes. So far, I have found this [Caller...] attribute injection to not work correctly in Client scripting, so I decided to use a more manual `string processName` parameter to be required for the shared TryProcess so I can still track the calling source in some manner.
