### ISSUE TITLE
nit: Why are the columns `*index`? Are all columns being index?

### ISSUE THREAD

**Issue by phuvp** [erikgassler/Demo#3]
https://github.com/erikgassler/Demo/blob/476af408a9ffa3ac61c1c604e8cd5d9e8c672819/WebApp/Server/Crypto/CSVLoader.cs#L49

**Comment by erikgassler** [comment]
> https://github.com/erikgassler/Demo/blob/476af408a9ffa3ac61c1c604e8cd5d9e8c672819/WebApp/Server/Crypto/CSVLoader.cs#L49

These constants represent index values for the `string[] columns` array variable above. Each data field is expected to be at a constant index position within that array so I mapped those positions to these variables to help self-document the code and be explicitly clear what data is expected at which index positions.
