### ISSUE TITLE
This would need to be activated to do the last 2 steps of the assignment.

### ISSUE THREAD

**Issue by phuvp** [erikgassler/Demo#5]
https://github.com/erikgassler/Demo/blob/476af408a9ffa3ac61c1c604e8cd5d9e8c672819/SqlScripts/Database.Demo.sql#L74

**Comment by phuvp** [comment]
```
Most cases the IngestionIsRunning flag should be enough to prevent duplicate running. For potential edge cases where 2 requests happen simultaneously and both processes get past the if (IngestionIsRunning)​ check then the lock (IngestionLock)​ will guarantee that only 1 will be allowed to run at 1 time. This would result in both getting run, but they would run sequentially, not in parallel.
```

The duplicate running wouldn't be a concern with snapshot isolation

**Comment by erikgassler** [comment]
> https://github.com/erikgassler/Demo/blob/476af408a9ffa3ac61c1c604e8cd5d9e8c672819/SqlScripts/Database.Demo.sql#L74

Good to know. I've never came across that feature before. I'll do more digging into it. I'd love to pick your brain more about it as well.
